### ISSUE TITLE
wrong minting amount

### ISSUE THREAD

**Issue by code423n4** [code-423n4/2022-01-behodler-findings#297]
# Handle

danb

# Vulnerability details

https://github.com/code-423n4/2022-01-behodler/blob/main/contracts/TokenProxies/RebaseProxy.sol#L36

```
uint256 proxy = (baseBalance * ONE) / _redeemRate;
```

should be:
```
uint256 proxy = (amount * ONE) / _redeemRate;
```

**Comment by gititGoro** [comment]
Fixed with https://github.com/Behodler/limbo/pull/17
